### PR TITLE
fix crash on iOS 8

### PR DESCRIPTION
**Pull request by MP0w**
Still not fully working on iOS 8 but at least it doesn't crash.
I'm detecting all problem and I will try to fix, did you plan to work on it to add iOS 8 compatibility?
If not, will you submit an eventual update in case I fix the issues?

Bye!

### CODE REVIEW

**Comment by mootjeuh** [comment]
Line 235 of IPC.m: applicationWithDisplayIdentifier: and applicationWithBundleIdentifier: are methods of SBApplicationController, not SBApplication

**Comment by MP0w** [comment]
@mootjeuh thanks, I was drunk! In that case application was always nil, but the if would have been false in any case and probably cause a crash on iOS 7 since in the else I call applicationWithBundleIdentifier: on the right object

**Comment by MP0w** [comment]
I close this PR since @mootjeuh already worked on the final solution for iOS 8 compatibility

**Comment by mootjeuh** [comment]
Haha maybe it helps that I'm drinking wine right now! Fight fire with fire eh?

**Pull request closed without merging**
